baseURL = 'https://sudheer.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'

# Theme
[module]
  [[module.imports]]
    path = 'github.com/rhazdon/hugo-theme-hello-friend-ng'
theme = "hugo-theme-hello-friend-ng"

[params.logo]
    logoMark = ">"
    logoText = "SuDo /home/"
[params.author]
    name = "SuDo"

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "posts"
        url = "posts/"
        weight = 60
    [[menu.main]]
        identifier = "about"
        name = "about"
        url = "about/"
        weight = 40
